-- Aula de Criação de tabelas. 


-- Tabela de clientes
CREATE TABLE [TABELA DE CLIENTES]
(
[CPF][CHAR](11),
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR](150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[GENERO] [CHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]
)

-- Tabela de vendedores

CREATE TABLE [TABELA DE VENDEDORES]
(
[MATRICULA] [CHAR] (5),
[NOME] [VARCHAR] (100),
[PERCENTUAL COMISSAO] [FLOAT]
)

--Tabela de produtos

CREATE TABLE [TABELA DE PRODUTOS]
(
[CODIGO DE PRODUTO] [VARCHAR](20),
[NOME DO PRODUTO] [VARCHAR] (150),
[EMBALAGEM] [VARCHAR] (50),
[TAMANHO] [VARCHAR] (50),
[SABOR] [VARCHAR] (50),
[PRECO DE LISTA] [SMALLMONEY]
);